language: node_js
node_js:
  - 13.10.0
  
services:
  - xvfb
  
before_install:
  - export DISPLAY=:99.0

before_script:
  - npm install
  
script: ./node_modules/.bin/karma start --browsers Firefox --single-run 
